jobs:
  test-and-sonarcloud:
    name: Run Tests and Trivy Scan
    runs-on: ubuntu-latest

    steps:
      # Cache the Trivy DB to avoid downloading it every time
      - name: Cache Trivy DB
        uses: actions/cache@v3
        with:
          path: ~/.cache/trivy
          key: ${{ runner.os }}-trivy-db-${{ hashFiles('**/trivy.db') }}
          restore-keys: |
            ${{ runner.os }}-trivy-db-

      # Run Trivy scan
      - name: Run Trivy Security Scan
        run: |
          trivy image --skip-update my-app:latest
