name: CI Pipeline with SonarCloud

on:
  push:
    branches:
      - main  # Runs on pushes to the main branch
  pull_request:
    branches:
      - main  # Runs on pull requests to the main branch

jobs:
  test-and-sonarcloud:
    name: Run Tests and SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use the Node.js version required by your Angular project

      - name: Install dependencies
        run: npm install

      - name: Start xvfb (for headless browsers)
        run: |
          sudo apt-get install xvfb
          export DISPLAY=':99.0'
          Xvfb :99 -ac &

      - name: Run tests and generate coverage report
        run: |
          npm run test -- --watch=false --code-coverage --browsers=ChromeHeadless
        env:
          CI: true  # Ensures tests run in CI mode (prevents interactive prompts)

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=firassaada_Simple_Angular_App
            -Dsonar.organization=firassaada
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.sources=src/app/modules
            -Dsonar.tests=src/app/tests
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info

      # Step to install ZAP
      - name: Install OWASP ZAP
        run: |
          sudo apt-get update
          sudo apt-get install -y zaproxy

      # Step to run ZAP security scan
      - name: Run OWASP ZAP Scan
        run: |
          # Run OWASP ZAP security scan on your deployed application
          zap-baseline.py -t http://localhost:4200 -r zap_report.html
        env:
          ZAP_API_KEY: ${{ secrets.ZAP_API_KEY }}  # Store your ZAP API key in GitHub secrets

      # Step to upload the ZAP report as artifact
      - name: Upload ZAP Report
        uses: actions/upload-artifact@v3
        with:
          name: zap-report
          path: zap_report.html
